### ISSUE TITLE
Getting Bucket Size

### ISSUE THREAD

**Issue by jbcintra** [oracle/oci-dotnet-sdk#121]
When calling BucketGet via SDK or CLI, ApproximateCount and ApproximateSize are always both null.

Looking at Metrics Explorer, I can select a compartment, select oci_objectstorage, choose a bucket, and can see bucketsize.

Going in via MonitoringClient SDK, passing in oci_objectstorage, and filters "resourceId" and the OCID of the bucket, the compartment etc... returns only details of the filters, and no actual data.   
Then I queried via CLI "oci monitoring metric list --compartment-id ***" to get a list of metrics in the compartment, and there is nothing for bucket size, StoredBytes etc?

Is the console display rendering bucketsize from some other source, not in the metrics? Either way, is there an SDK way to get the bucket size?  The auto-generated code examples are incredibly generic, so not providing useful insight.

**Comment by jbcintra** [comment]
Reading down the output file (from CLI), I'd not added --all, adding that got the metric StoredBytes listed, but still no response from the SDK call. Do I have to explicitly add search dates, aggregate to 1d etc?

**Comment by github-anurag** [comment]
Hi @jbcintra 
Thank you for bringing this up. I will forward this question to the Object Storage team.

**Comment by github-anurag** [comment]
Hi @jbcintra 
Can you try setting the Fields enum in the Request. This would enable you to get this information. Sample code:-
```
        const string OciConfigProfileName = "DEFAULT";
        private static NLog.Logger logger = NLog.LogManager.GetCurrentClassLogger();

        public static async Task Main()
        {
            // Accepts profile name and creates a auth provider based on config file
            var provider = new ConfigFileAuthenticationDetailsProvider(OciConfigProfileName);
            // Create a client for the service to enable using its APIs
            var client = new ObjectStorageClient(provider, new ClientConfiguration());

            try
            {
                var getBucketResponse = await client.GetBucket(new GetBucketRequest
                {
                    BucketName = "Bucket-Name",
                    NamespaceName = "Namespace-Name",
                    Fields = new List<GetBucketRequest.FieldsEnum>
                    {
                        GetBucketRequest.FieldsEnum.ApproximateCount,
                        GetBucketRequest.FieldsEnum.ApproximateSize,
                        GetBucketRequest.FieldsEnum.AutoTiering
                    }
                });
                logger.Info($"Bucket Size:{getBucketResponse.Bucket.ApproximateSize}");
            }
            catch (Exception e)
            {
                logger.Info($"Received exception due to {e.Message}");
            }
            finally
            {
                client.Dispose();
            }
```
I believe this will resolve your issue. Please feel free to open this if you still see the issue.

**Comment by jbcintra** [comment]
Thanks @github-anurag, that worked in code by itself. Does that mean the field is only enumerated when it's specifically triggered in this way? I'll look at adding it into my GetBucket function, so it pulls it for each bucket.

Much appreciated & much easier!

**Comment by github-anurag** [comment]
@jbcintra 
Yes, that is how it has been designed. I am not sure about the specifics that went into making this design choice, however, my best guess is that it is related to performance.

**Comment by jbcintra** [comment]
for info, I just created a fields variable, then added that into the request object in my main audit code, it's gone & pulled the bucketsize across a load of buckets without problem!  Thanks again.

**Comment by github-anurag** [comment]
For CLI you can use the following for eg:-
```
oci os bucket get  --bucket-name "bucket-name" --namespace-name "namespace-name" --fields "approximateSize" --fields "autoTiering
```

**Comment by jbcintra** [comment]
Thanks @github-anurag, I'll pass that one onto our ops guys for doing quick checks!
