### ISSUE TITLE
InstancePrincipleExample fails with ArgumentNullException exception

### ISSUE THREAD

**Issue by 55v** [oracle/oci-dotnet-sdk#15]
While trying the InstancePrincipal example, I received an AgumentNullException after the following WARN message in console:

> 2020-09-09 10:03:14.4724|WARN|Oci.Common.Auth.AbstractRequestingAuthenticationDetailsProvider|Received exception: System.ArgumentException: Unable to find region from regionId .

It seems like http://169.254.169.254/opc/v2/instance/region URLs returns regionId ("eu-frankfurt-1" in my case) while this code expects region code ("fra"):
https://github.com/oracle/oci-dotnet-sdk/blob/56b2b30c209d9ca716c2a45a4b9f7314a4ac95ba/Common/Src/Auth/AbstractRequestingAuthenticationDetailsProvider.cs#L134

**Comment by varunmankal** [comment]
@55v Thank you for trying this out. 

we understand the issue and the fix will be in next week's release.

**Comment by varunmankal** [comment]
@55v we have fixed the bug in the latest release: https://github.com/oracle/oci-dotnet-sdk/releases/tag/v4.4.0 .
Please try this out and let us know if there are any issues.
Thank you.
