### ISSUE TITLE
OrganizationsClient -> ListOrganizations (rootId), stuck when listing All

### ISSUE THREAD

**Issue by jbcintra** [oracle/oci-dotnet-sdk#155]
Hi, pulling via latest SDK, OrganizationsClient -> ListOrganizations(rootId).  In the SDK, calling via the client paginator, it just hangs and is in some loop.

Via the CLI, without the "-all" flag, it returns a single record without problem.

Via both the SDK paginator and the CLI with "-all" flag, the API hangs and does not respond, seemingly in a loop.

**Comment by jbcintra** [comment]
Changing the code to get the .First() response works ok .... but all in both SDK/API are failing still.

**Comment by github-anurag** [comment]
@jbcintra 
Just to confirm is the API also failing with CLI with -all flag?

**Comment by jbcintra** [comment]
Yes, the following is fine:
oci organizations organization list --compartment-id ocid1.tenancy.oc1..**** --profile ***

The following just sits there forever...
oci organizations organization list --compartment-id ocid1.tenancy.oc1..**** --all --profile ****

**Comment by github-anurag** [comment]
Thanks @jbcintra for reporting this issue. I can reproduce this as well on my end. Will forward this issue to the organizations team to investigate more on this.

**Comment by jbcintra** [comment]
Thanks @github-anurag ...

**Comment by jbcintra** [comment]
Hi @KartikShrikantHegde , just checked on the tooling and yes this has kicked into life now.   Handy as we look to implement orgs, child tenancies and domains with customers.  Many thanks, Justin
