### ISSUE TITLE
How to get the Url of a storage object?

### ISSUE THREAD

**Issue by migueloliveiradev** [oracle/oci-dotnet-sdk#174]
I'm storing some objects, but in the put and get of an object I didn't find any way in the documentation to return the url, I'm having to assemble it manually, how can I return the url?

```cs
string url = $"https://objectstorage.{Environment.GetEnvironmentVariable("OCI_REGION_ID")}" +
                $".oraclecloud.com/n/{Environment.GetEnvironmentVariable("NAMESPACE_NAME")}" +
                $"/b/{Environment.GetEnvironmentVariable("BUCKET_NAME")}/o/projects/{url}"
```

**Comment by github-anurag** [comment]
@migueloliveiradev 
The Objectstorage API does not return the URL in any of the response as you have stated. Currently, there is no good way to get the URL apart from building it manually. 
PS: The `oraclecloud.com` in your manual code is only valid for OC1 Realms.
