### ISSUE TITLE
Missing OkeWorkloadIdentityAuthenticationDetailsProvider 

### ISSUE THREAD

**Issue by tb137** [oracle/oci-dotnet-sdk#180]
Hi, correct me if  I am wrong, but dotnet sdk is missing function "OkeWorkloadIdentityAuthenticationDetailsProvider" in auth library. It does exist in go and java sdks...

Does that mean that dotnet sdk do not support OKE workload identity auth ?

T.

**Comment by github-anurag** [comment]
Hi @tb137 ,
Yes, that is correct the OKE workload identity is currently only supported in Java and Python SDK.

**Comment by tb137** [comment]
Is there a plan to make it available any time soon?

**Comment by KartikShrikantHegde** [comment]
Hi @tb137 , not immediately, but we do hope to take it up at a future date. Thanks.
