### ISSUE TITLE
Calling GetSecretBundleByName from behind a proxy

### ISSUE THREAD

**Issue by Ashu1985** [oracle/oci-dotnet-sdk#193]
I am doing a code to call GetSecretBundleByName, code is working fine from my local system, but not able to make calls if machine is behind proxy.

With Ruby I can do this like 
proxy_setting = OCI::ApiClientProxySettings.new("HOST", PORT)
config = OCI::ConfigFileLoader.load_config(config_file_location: "D:\\config", profile_name: 'DEFAULT') 
secrets_client = OCI::Secrets::SecretsClient.new(config: config, proxy_settings: proxy_setting) 
get_secret_bundle_by_name_response =  secrets_client.get_secret_bundle_by_name( ... )

Need to know the equivalent way for C#
My C# code is 

var provider = new ConfigFileAuthenticationDetailsProvider("D:\\config", "DEFAULT");
try
{
      var getSecretBundleRequest = new Oci.SecretsService.Requests.GetSecretBundleByNameRequest
      {
                    VaultId = V_ID,
                    SecretName = S_NAME
       };

        using (var client = new SecretsClient(provider, new ClientConfiguration()))
        {                    
                var response = await client.GetSecretBundleByName(getSecretBundleRequest);
                Base64SecretBundleContentDetails secretIdValue = (Base64SecretBundleContentDetails)response.SecretBundle.SecretBundleContent;
                 string encodedString = secretIdValue.Content;
         }
}

**Comment by github-anurag** [comment]
@Ashu1985 
The HttpClient uses the Proxy set via the environment variables in your system.
Refer: https://learn.microsoft.com/en-us/dotnet/api/system.net.http.httpclient?view=netstandard-2.0#proxies 

You can check the variables you can set to enable proxy here:-
https://learn.microsoft.com/en-us/dotnet/api/system.net.http.httpclient.defaultproxy?view=net-7.0&viewFallbackFrom=netstandard-2.0#system-net-http-httpclient-defaultproxy

**Comment by jyotisaini** [comment]
Hi @Ashu1985  did it fix the issue for you ?

**Comment by github-anurag** [comment]
@Ashu1985 
We are closing this issue. Please feel free to re-open if this issue has not been resolved for you.
