### ISSUE TITLE
PrivateKeySupplier missing support for AsymmetricKeyParameter

### ISSUE THREAD

**Issue by nimoskov** [oracle/oci-dotnet-sdk#195]
After creating a private key for my user I downloaded the PEM file and initialized the FilePrivateKeySupplier with it and everything worked.
Now I store the content encrypted in my DB and get the content on runtime and want to use it with PrivateKeySupplier.
For some reason the PrivateKeySupplier assumes the key is AsymmetricCipherKeyPair and doesn't support the AsymmetricKeyParameter option like the FilePrivateKeySupplier.
Fixing it can be relatively easy, move the code from FilePrivateKeySupplier to PrivateKeySupplier and make FilePrivateKeySupplier inherit from PrivateKeySupplier

This is the code that can be moved to PrivateKeySupplier
```
var obj = new PemReader((TextReader) new StringReader(this.privateKeyContent), this.passPhrase == null ? (IPasswordFinder) null : (IPasswordFinder) new PasswordFinder(this.passPhrase)).ReadObject();
switch (obj)
{
    case AsymmetricCipherKeyPair _:
        return this.privateKey = (RsaKeyParameters) ((AsymmetricCipherKeyPair) obj).Private;
    case AsymmetricKeyParameter _:
        RsaPrivateCrtKeyParameters crtKeyParameters = (RsaPrivateCrtKeyParameters) obj;
        return this.privateKey = new RsaKeyParameters(crtKeyParameters.IsPrivate, crtKeyParameters.Modulus, crtKeyParameters.Exponent);
    default:
        throw new FormatException("The given key does not have the expected type");
}
```

Do you agree with the change? 
I can make a PR if you do

Thanks

**Comment by github-anurag** [comment]
Resolved in 86.0.0
