### ISSUE TITLE
Cost and Usage Reports Overview

### ISSUE THREAD

**Issue by elyosemite** [oracle/oci-dotnet-sdk#225]
Is there a nuget within the OCI SDK that has the responsibility of handling OCI cloud service cost and usage data? I need to treat and do calculation geared towards **FinOps** and; therefore, the need for an SDK aimed at this segment arose; but I'm not sure if the OCI SDK.DotNetSDK.Usage solves this problem.

**Comment by github-anurag** [comment]
@elyosemite 
Please refer the page [Cost Analysis using API](https://docs.oracle.com/en-us/iaas/Content/Billing/Concepts/costanalysisoverview.htm#cost_analysis_using_the_api ), it has relevant information on how to use the Usage API.
The OCI Dotnet SDK should support all the APIs mentioned under the [Usage Service](https://docs.oracle.com/en-us/iaas/api/#/en/usage/20200107/) in the OCI API Reference
Once you have the exact API you need to use for your usecase, we can provide you some examples for you to refer. If there is no suitable API that works for your usecase then you may need to work with an OCI Solutions teams.

Closing this issue, as it is a query and not an issue with the OCI Dotnet SDK itself.
