### ISSUE TITLE
get object size on bucket

### ISSUE THREAD

**Issue by joaopintof** [oracle/oci-dotnet-sdk#260]
Hello everyone, i'm trying to get the object size using this  method ListObjects. but the Size is empty here.
Could you help me please?

the goal is show to my customer the total size usage on the bucket.

 the bucket is:

customer1/year/month/day ... files..
customer2/year/month/day ... files..
customer3/year/month/day ... files..
... 
...

 

`public static async Task<string> GetClientStorageUsageByPrefixAsync(ObjectStorageClient client, string namespaceName, string bucketName,string clientPrefix)
        {
            long totalSizeInBytes = 0;
            long totalFiles = 0;

            string start = null;
            do
            {
                var listObjectsRequest = new ListObjectsRequest
                {
                    NamespaceName = namespaceName,
                    BucketName = bucketName,
                    Prefix = clientPrefix,
                    Start = start
                };

                ListObjectsResponse listObjectsResponse = await client.ListObjects(listObjectsRequest);               
                foreach (var obj in listObjectsResponse.ListObjects.Objects)
                {
                    totalSizeInBytes += obj.Size ?? 0;
                    Console.WriteLine($"Arquivo: { obj.Name } - Tamanho: {obj.Size}");
                    totalFiles++;
                }

                start = listObjectsResponse.ListObjects.NextStartWith;
            } while (!string.IsNullOrEmpty(start));

            double totalSizeInGB = totalSizeInBytes / 1_073_741_824.0;
            return totalSizeInGB + " GB / " + totalFiles + " arquivos";
        }`

**Comment by github-anurag** [comment]
@joaopintof 
Please refer to: https://github.com/oracle/oci-dotnet-sdk/issues/121 for a solution to this problem

You need to populate the `fields` parameter as well to get the desired response.
Refer: https://docs.oracle.com/en-us/iaas/api/#/en/objectstorage/20160918/Object/ListObjects 

This is by design to improve performance of the APIs.

**Comment by joaopintof** [comment]
niceeee...tks a lot @github-anurag 

it works here :-)
