### ISSUE TITLE
Instance Principal Auth?

### ISSUE THREAD

**Issue by Gerr-Alt** [oracle/oci-dotnet-sdk#3]
Thanks for amazing news with the SDK for the .NET!
Can you please tell, is there any possibility to use Instance Principal authorization? If not, when do you plan to support it?
Our project is highly depends on the .NET stack, and we will need to use Instance Principal auth from the each our VM.

Thanks in advance!

**Comment by buzhidao77** [comment]
@Gerr-Alt instance principal will be among the next bunch of features that will go in. We understand the need and will be working diligently to deliver it. 
Thanks.

**Comment by buzhidao77** [comment]
@Gerr-Alt  We have released Instance Principal in v4.3.0. Here's [an example on how to use Instance Principal](https://github.com/oracle/oci-dotnet-sdk/blob/master/Examples/InstancePrincipalExample.cs)
