### ISSUE TITLE
Invalid queries created in .Net Framework projects

### ISSUE THREAD

**Issue by 55v** [oracle/oci-dotnet-sdk#4]
Steps to reproduce.

Create new Console App (.NET Framework) project, add following code to Main method:

```
var computeClient = new ComputeClient(new ConfigFileAuthenticationDetailsProvider("DEFAULT"), new ClientConfiguration());
var listShapesRequest = new ListShapesRequest
{
	CompartmentId = "compartment_id_here",
	AvailabilityDomain = "AD_name_here"
};
ListShapesResponse listShapesResponse = computeClient.ListShapes(listShapesRequest).Result;

```
Example fails with OciException: "Missing compartmentId"

HttpUtils.BuildQueryString Creates query string with starting "?", see
https://github.com/oracle/oci-dotnet-sdk/blob/6009c5903fc81995e4f4127ad1307d8ca78ab1fc/Common/Src/Utils/HttpUtils.cs#L88
This works fine in dotnet core, but fails in .Net Framework. It seems like System.UriBuilder.Query string setter works differently in dotnet core, see
https://github.com/dotnet/runtime/blob/6072e4d3a7a2a1493f514cdf4be75a3d56580e84/src/libraries/System.Private.Uri/src/System/UriBuilder.cs#L278
and .Net Framework, see
https://github.com/microsoft/referencesource/blob/a7bd3242bd7732dec4aebb21fbc0f6de61c2545e/System/net/System/uribuilder.cs#L277

**Comment by buzhidao77** [comment]
Let me take a look.

**Comment by buzhidao77** [comment]
@55v Thanks for raising this issue. The fix will come in our next week's release.

**Comment by varunmankal** [comment]
Closing this issue as it is fixed.

**Comment by buzhidao77** [comment]
@55v The fixed is in. Please give it a try. Feel free to reopen if the problem still exists. 

Thanks

**Comment by 55v** [comment]
Works now, thank you!
