### ISSUE TITLE
Cannot utilize 'using' on ClientBase type variable

### ISSUE THREAD

**Issue by 55v** [oracle/oci-dotnet-sdk#6]
The ClientBase class has Dispose method but does not implement IDisposable interface, so C# compiler does not allow to utilize 'using' statement for ClientBase variables:
https://github.com/oracle/oci-dotnet-sdk/blob/6009c5903fc81995e4f4127ad1307d8ca78ab1fc/Common/Src/ClientBase.cs#L17-L65

**Comment by buzhidao77** [comment]
@55v Thanks for raising this issue. We'll update with a fix in our next release.

**Comment by buzhidao77** [comment]
@55v release version 2.0.0 contains the fix to this issue. Please feel free to reopen if the problem still exists.

**Comment by varunmankal** [comment]
Closing this issue as it is fixed in 2.0.0 version.
