### ISSUE TITLE
Performance regression in versions 14.2.0 to 22.0.0 for some services (fixed in v23.0.0)

### ISSUE THREAD

**Issue by github-anurag** [oracle/oci-dotnet-sdk#63]
In versions 14.2.0 to 22.0.0, you may encounter performance regressions when using the SDK with some OCI services. This issue has been fixed in v23.0.0 and later versions.

The regression surfaces itself as a 1-second increase in latency in SDK operations made to some OCI services. This issue has been confirmed to impact the OCI Streaming service, and likely impacts the Email Delivery, Health Checks, NoSQL Database Cloud, Registry, Generic Artifacts, and Web Application Acceleration and Security services as well. This list is not comprehensive – it is possible you may encounter the issue against other OCI services as well. The issue has been confirmed to NOT affect the OCI Object Storage and Functions services.

If you are experiencing this issue there are some workarounds you can do:
- Use SDK version 14.1.0 or earlier, or version 23.0.0 later
- Or, use the SDK's raw request signer to make requests to OCI services for any requests where you are experiencing performance degradation. An example on how to use the raw request signer is [here](https://github.com/oracle/oci-dotnet-sdk/blob/master/Examples/RawRestCallExample.cs)

**Comment by jodoglevy** [comment]
This issue has been fixed in v23.0.0

**Comment by mr-russ** [comment]
If this has been fixed in v23.0.0, can this issue be closed?
