### ISSUE TITLE
Usageapi - query single days costs - date format precision issue

### ISSUE THREAD

**Issue by jbcintra** [oracle/oci-dotnet-sdk#67]
Hi,
I'm looking to pull costs for a single compartment for 1 day, to see what the output is, and then look at tuning to get a specific set of costs.
Following the example code posted, passing in datetimes via DateTime.Parse, I get datetime precision errors.

TimeUsageStarted = DateTime.Parse("2021 JUL 21 00:00:00")
TimeUsageEnded = DateTime.Parse(2021 JUL 21 23:59:59")

These come out as valid DateTime objects, but when passed in to DTS/DTE the precision error arises.

Do you have an example lean query (ie without every single possible parameter/option, just the required ones) to output the costs for a compartment or tenant for a day?  From that wide starter I can then filter down to compute, storage etc, and tag grouping.

Thanks, Justin.

**Comment by buzhidao77** [comment]
Hi @jbcintra Could you please let us know which request is having the datetime precision errors?

**Comment by jbcintra** [comment]
Hi @buzhidao77 ,  creating a new CreateQueryDetails as per the example in your documentation: https://docs.oracle.com/en-us/iaas/tools/dot-net-examples/23.0.0/usageapi/CreateQuery.cs.html.

It errors at the "var response = await ..."

My initial code is...
public async Task<string> CreateQuery()
		{

			var start = DateTime.Parse("2021 JUL 21 00:00:00");
			var end = DateTime.Parse("2021 JUL 21 23:59:59");

			var createQueryDetails = new CreateQueryDetails()
			{
				// management compartment
				CompartmentId = "ocid1.compartment.oc1..**********",
				QueryDefinition = new QueryDefinition()
				{
					DisplayName = "JB-Test-Query",
					Version = 1,
					ReportQuery = new ReportQuery()
					{
						TenantId = "ocid1.tenancy.oc1..******",
						TimeUsageStarted = start,
						TimeUsageEnded = end,
						Granularity = ReportQuery.GranularityEnum.Daily,
						IsAggregateByTime = true,
						QueryType = ReportQuery.QueryTypeEnum.Cost,
						GroupByTag = new List<Tag>
						{
							new Tag()
							{
								Namespace = "namespace1",
								Key = "key1"
							}
						},
						CompartmentDepth = 1
					},
					CostAnalysisUI = new CostAnalysisUI
					{
						Graph = CostAnalysisUI.GraphEnum.StackedLines,
						IsCumulativeGraph = false
					}
				}
			};

			var createQueryRequest = new CreateQueryRequest
			{
				CreateQueryDetails = createQueryDetails,
				OpcRequestId = "JB-REQ-TEST-12345"
			};

			var response = await _client.CreateQuery(createQueryRequest);
			var id = response.Query.Id;

			return id;
		}

**Comment by buzhidao77** [comment]
Thanks @jbcintra We will look into this and get back to you.

**Comment by github-anurag** [comment]
@jbcintra 
Can you also share the stack trace error you have observed.

**Comment by jbcintra** [comment]
The Exception.StackTrace doesn't have too much in it... no inner exception or OciException
StackTrace = "   at Oci.Common.Http.Internal.ResponseHelper.HandleNonSuccessfulResponse(HttpResponseMessage responseMessage)\r\n   at Oci.Common.Http.RestClient.CheckHttpResponseMessage(HttpRequestMessage httpRequest, HttpResponseMessage httpResponse)\r\n   at Oci.Usage...

I'm getting strange responses now, it's firing an Error without an OciException inner exception...  and it's just killing my code, even with a Try around the "var response" line, the code just stops dead, doesn't carry on?

I've got code processing almost 400 OCI APIs so far, all without problem... but this one just dies... I'll try to get the outer exception out of VS before it drops

**Comment by jbcintra** [comment]
And right after that, my logging caught an exception ...
Oci.Common.Model.OciException: Passed date does not have the right precision     
at Oci.Common.Http.Internal.ResponseHelper.HandleNonSuccessfulResponse(HttpResponseMessage responseMessage)     
at Oci.Common.Http.RestClient.CheckHttpResponseMessage(HttpRequestMessage httpRequest, HttpResponseMessage httpResponse)     
at Oci.UsageapiService.UsageapiClient.CreateQuery(CreateQueryRequest request, RetryConfiguration retryConfiguration, CancellationToken cancellationToken)     
at cintra_oci_extract_sdk.Oci.OciUsage.CreateQuery() in C:\Users\justi\source\repos\cintra-oci\cintra-oci-extract-sdk\Oci\OciUsage.cs:line 81

**Comment by honniu** [comment]
For getting usage/cost data, you are using wrong API. 
You can use https://docs.oracle.com/en-us/iaas/api/#/en/usage/20200107/UsageSummary/RequestSummarizedUsages 
For datetime format, you can follow
`Using granularity
The Usage API supports: MONTLY, DAILY, and HOURLY granularity. All startTime are inclusive, and endTime are exclusive, the same as a Java substring.

For HOURLY, only a maximum 36-hour time period is supported, with no more precision than an hour. This means no minutes or seconds in the input time.
For MONTHLY, only the first date of the month to another first date of the month is supported. For example, 2020-06-01T00:00:00Z, a maximum 12-month period.

For DAILY, no more precision than a day is supported, with a maximum 90-day period. You must enter this as 00:00:00. For example, 2020-06-01T00:00:00Z.`

For more instruction, you can check https://docs.oracle.com/en-us/iaas/Content/Billing/Concepts/costanalysisoverview.htm#Cost_Analysis_Overview and scroll down to the end. There are some explanation.

**Comment by jbcintra** [comment]
Thanks @honniu!  I'll give that one a go tomorrow! :)

**Comment by github-anurag** [comment]
Hi @jbcintra,

This example might help you get started:-
```
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Oci.UsageapiService;
using Oci.UsageapiService.Models;
using Oci.UsageapiService.Requests;
using Oci.UsageapiService.Responses;

using Oci.Common;
using Oci.Common.Auth;

namespace Oci.Examples
{
    public class UsageApiExample
    {
        private static NLog.Logger logger = NLog.LogManager.GetCurrentClassLogger();
        const string OciConfigProfileName = "DEFAULT";
        public static async Task Main()
        {
            logger.Info("Starting example");
            // Assumption: the compartment id has been set in environment variable.
            string tenantId = Environment.GetEnvironmentVariable("OCI_TENANT_ID");
            var provider = new ConfigFileAuthenticationDetailsProvider(OciConfigProfileName);

            var client = new UsageapiClient(provider, new ClientConfiguration());
            try
            {
                RequestSummarizedUsagesResponse response = await GetSummarizedUsage(client, tenantId);
                logger.Info($"Response count:{response.UsageAggregation.Items.Count}");
                List<UsageSummary> items = response.UsageAggregation.Items;
                foreach (UsageSummary item in items)
                {
                    logger.Info($"Compartment name:{item.CompartmentName}");
                    logger.Info($"Amount:{item.ComputedAmount}");
                }
            }
            catch (Exception e)
            {
                logger.Info($"Received exception due to {e.Message}");
            }
            finally
            {
                client.Dispose();
            }
        }

        public static async Task<RequestSummarizedUsagesResponse> GetSummarizedUsage(UsageapiClient client, string tenantId)
        {
            DateTime start = new DateTime(2021, 7, 21, 0, 0, 0, DateTimeKind.Utc);
            DateTime end = new DateTime(2021, 8, 21, 0, 0, 0, DateTimeKind.Utc);
            var requestSummarizedUsagesDetails = new Oci.UsageapiService.Models.RequestSummarizedUsagesDetails
            {
                TenantId = tenantId,
                TimeUsageStarted = start,
                TimeUsageEnded = end,
                Granularity = RequestSummarizedUsagesDetails.GranularityEnum.Daily,
                IsAggregateByTime = true,
                QueryType = RequestSummarizedUsagesDetails.QueryTypeEnum.Cost,
                GroupBy = new List<string> { "service", "skuName" }

            };

            var requestSummarizedUsagesRequest = new RequestSummarizedUsagesRequest
            {
                RequestSummarizedUsagesDetails = requestSummarizedUsagesDetails
            };

            return await client.RequestSummarizedUsages(requestSummarizedUsagesRequest);
        }
    }
}


```

**Comment by jbcintra** [comment]
Hi @github-anurag , thanks for that too... be nice to get it working, easier than pulling masses of data from OS to process, much cleaner! Cheers, Justin

**Comment by jbcintra** [comment]
Hi @github-anurag, I've tried your code in a separate app to test, and am getting 500 errors from OCI UK for a couple of tenancies.  Tried a US tenancy, but I've not got permissions, so request in to get that permission added to my US account.

Trying via the console and that query works fine, so the API itself is fine in the UK.

Will dig in more.

**Comment by github-anurag** [comment]
@jbcintra 
Were you able to resolve this issue?

**Comment by jbcintra** [comment]
Hi @github-anurag , I tried again yesterday with no joy.  I was able to replicate the query with the same parameters in the CLI, so it's not an API or permissions problem.  I've fired the C# & CLI command & Log output over to product management to see if they can find where the issue is.  They should work the same as they will back onto the same API, but apparently not. This was tested in the UK against a number of tenancies.

I'll update when I hear back.

**Comment by jbcintra** [comment]
I've tested the CLI command & C# sample code against a US tenancy in Phoenix, same result. CLI works, C# gives a 500 error.

**Comment by honniu** [comment]
what's the requestId with the 500 error?

**Comment by jbcintra** [comment]
Hi @honniu , in Phoenix it is
  opc-request-id: /CCDFB7D02E6F2D42463D23B31B012EB5/0EFC376EAFB6E4698AC3BE55FB5C1428

**Comment by honniu** [comment]
I can't find the request in our system. Usually, a normal request id hitted server side will have three parts like /CCDFB7D02E6F2D42463D23B31B012EB5/0EFC376EAFB6E4698AC3BE55FB5C1428/xxxxxxxx. I think it is because your c# code failed to create the auth provider or using wrong configuration.

**Comment by jbcintra** [comment]
I'll put my standard auth code in, instead of the code provided further up the chat.

**Comment by jbcintra** [comment]
I've ported the Usage query into my own code, using my own authentication code. A credentials failure should not result in a 500 error.  I had trial & error creating creds in memory from a source, to keep creds secure and off disk, but never received a 500 error during that process.

Just sorting another run now, against the US tenancy.

**Comment by jbcintra** [comment]
It's 500 error, definitely not credentials, as this same code queries out Usage.ListQueries and hundreds of other aspects of OCI with the same credentials setup.

2021-07-27 18:07:30.431 +01:00 [INF] Executing >> ProcessOciExtractionSdk.ProcessUsage for msptargetbase01
2021-07-27 18:07:51.934 +01:00 [ERR] One or more errors occurred. (Internal Service Error, please try again)
2021-07-27 18:07:52.022 +01:00 [WRN] **tenant** 500 InternalServerError, GetSummarizedUsageV2(103) >> ProcessUsage(4332) >> 
System.AggregateException: One or more errors occurred. (Internal Service Error, please try again)
 ---> Oci.Common.Model.OciException: Internal Service Error, please try again
   at Oci.Common.Http.Internal.ResponseHelper.HandleNonSuccessfulResponse(HttpResponseMessage responseMessage)
   at Oci.Common.Http.RestClient.CheckHttpResponseMessage(HttpRequestMessage httpRequest, HttpResponseMessage httpResponse)
   at Oci.UsageapiService.UsageapiClient.RequestSummarizedUsages(RequestSummarizedUsagesRequest request, RetryConfiguration retryConfiguration, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at cintra_oci_extract_sdk.Oci.OciUsage.GetSummarizedUsageV2(String tenantId) in C:\Users\justi\source\repos\cintra-oci\cintra-oci-extract-sdk\Oci\OciUsage.cs:line 103
   at cintra_oci_extract_sdk.ProcessOciExtractionSdk.ProcessUsage(Compartment root) in C:\Users\justi\source\repos\cintra-oci\cintra-oci-extract-sdk\ProcessOciExtractionSdk.cs:line 4332
2021-07-27 18:07:52.025 +01:00 [INF] OCI Extract via SDK Ended

**Comment by honniu** [comment]
@github-anurag is the example https://github.com/oracle/oci-dotnet-sdk/issues/67#issuecomment-885202908 working? From the requestId, the request didn't send out and we don't have any 5xx in last few hours.

**Comment by github-anurag** [comment]
@jbcintra Did you use the sample code I used or are you using something else?
Can we enable logs to see if there is issue in some other areas. Refer section Enable logging in https://docs.oracle.com/en-us/iaas/Content/API/SDKDocs/dotnetsdkgettingstarted.htm for more info

**Comment by jbcintra** [comment]
Hi @github-anurag , yes I used the sample code, which was giving 500 errors. I've just ported that function into my own codebase, with my identity code which is working.  It ran the Usage ListQueries which worked, then tried to run RequestSummarizedUsages from the code posted here, and got a 500 error. This was against a UK tenancy in the past few minutes. OpcRequestId included JBCINTRARSUD

**Comment by github-anurag** [comment]
@jbcintra can you please provide us the complete log and source for helping us debug this better.
PS: If possible please enable TRACE level logs.
more info on logging at the Enable logging section in https://docs.oracle.com/en-us/iaas/Content/API/SDKDocs/dotnetsdkgettingstarted.htm for more info

**Comment by honniu** [comment]
Hi @jbcintra , there is a issue on server side and we will fix it soon.
For mitigating your issue, you can change
`IsAggregateByTime = false` or remove the line.

**Comment by jbcintra** [comment]
Thanks @honniu , just tried it with that set to false and it extracted the data without problems.

**Comment by github-anurag** [comment]
@jbcintra 
The Service team has deployed a fix for the `IsAggregateByTime` issue. Let us know if you still see issue for it.

**Comment by jbcintra** [comment]
Thanks @github-anurag , I'll try a run with it set tomorrow

**Comment by jbcintra** [comment]
Hi @github-anurag, I've run the extract again with IsAggregatedByTime = true, and the report has run and aggregated figures for the extraction period as expected. Thanks!
