### ISSUE TITLE
CimsService / Support Management API - SSL failure, remote certificate invalid

### ISSUE THREAD

**Issue by jbcintra** [oracle/oci-dotnet-sdk#70]
Hi,

I've just been looking to extract OCI CSI support data for management reporting.  Code is setup as per the example, yet I'm getting the following back - from both uk-london-1 and us-phoenix-1 region settings.

I am passing in our CSI, customer root tenancyId, tried 2 homeregions (API documentation only lists 2 US sites?), my user OCID.

System.AggregateException: One or more errors occurred. (**The SSL connection could not be established, see inner exception.**)
 ---> System.Net.Http.HttpRequestException: The SSL connection could not be established, see inner exception.
 ---> System.Security.Authentication.AuthenticationException: **The remote certificate is invalid according to the validation procedure: RemoteCertificateNameMismatch**
   at System.Net.Security.SslStream.SendAuthResetSignal(ProtocolToken message, ExceptionDispatchInfo exception)
   at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](TIOAdapter adapter, Boolean receiveFirst, Byte[] reAuthenticationData, Boolean isApm)
   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsyncCore(Boolean async, Stream stream, SslClientAuthenticationOptions sslOptions, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsyncCore(Boolean async, Stream stream, SslClientAuthenticationOptions sslOptions, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttpConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.SendAsyncCore(HttpRequestMessage request, HttpCompletionOption completionOption, Boolean async, Boolean emitTelemetryStartStop, CancellationToken cancellationToken)
   at Oci.Common.Http.RestClient.HttpSend(HttpRequestMessage httpRequest, CancellationToken cancellationToken)
   at Oci.Common.Retry.GenericRetrier.<>c__DisplayClass3_0.<<MakeRetryingCall>b__4>d.MoveNext()
--- End of stack trace from previous location ---
   at Polly.Retry.AsyncRetryEngine.ImplementationAsync[TResult](Func`3 action, Context context, CancellationToken cancellationToken, ExceptionPredicates shouldRetryExceptionPredicates, ResultPredicates`1 shouldRetryResultPredicates, Func`5 onRetryAsync, Int32 permittedRetryCount, IEnumerable`1 sleepDurationsEnumerable, Func`4 sleepDurationProvider, Boolean continueOnCapturedContext)
   at Polly.AsyncPolicy`1.ExecuteAsync(Func`3 action, Context context, CancellationToken cancellationToken, Boolean continueOnCapturedContext)
   at Polly.Wrap.AsyncPolicyWrapEngine.<>c__DisplayClass2_0`1.<<ImplementationAsync>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at Polly.Timeout.AsyncTimeoutEngine.ImplementationAsync[TResult](Func`3 action, Context context, CancellationToken cancellationToken, Func`2 timeoutProvider, TimeoutStrategy timeoutStrategy, Func`5 onTimeoutAsync, Boolean continueOnCapturedContext)
   at Polly.Timeout.AsyncTimeoutEngine.ImplementationAsync[TResult](Func`3 action, Context context, CancellationToken cancellationToken, Func`2 timeoutProvider, TimeoutStrategy timeoutStrategy, Func`5 onTimeoutAsync, Boolean continueOnCapturedContext)
   at Polly.AsyncPolicy.ExecuteAsync[TResult](Func`3 action, Context context, CancellationToken cancellationToken, Boolean continueOnCapturedContext)
   at Polly.Wrap.AsyncPolicyWrapEngine.ImplementationAsync[TResult](Func`3 func, Context context, CancellationToken cancellationToken, Boolean continueOnCapturedContext, IAsyncPolicy outerPolicy, IAsyncPolicy`1 innerPolicy)
   at Polly.AsyncPolicy`1.ExecuteAsync(Func`3 action, Context context, CancellationToken cancellationToken, Boolean continueOnCapturedContext)
   at Oci.CimsService.IncidentClient.ListIncidents(ListIncidentsRequest request, RetryConfiguration retryConfiguration, CancellationToken cancellationToken)
   at Oci.Common.Utils.ResponseEnumerable`2.GetNextPageResponseAsync(String nextPageToken)
   at Oci.Common.Utils.ResponseEnumerable`2.<>c__DisplayClass4_0.<<GetEnumerator>b__0>d.MoveNext()
   --- End of inner exception stack trace ---

**Comment by github-anurag** [comment]
Hi @jbcintra 
Can you please share the example or the link you are using for trying this?

**Comment by jbcintra** [comment]
Hi @github-anurag , I'm not using a link.  I've tried initially via the CLI to see what data it returned, then via the SDK to see if I could connect, or get a clearer error...

**CLI**
oci support incident list --compartment-id ocid1.tenancy.oc1..***  --csi ******* --ocid ocid1.user.oc1..*** --all --profile ****

**CLI ERROR OUTPUT**

WARNING:oci._vendor.urllib3.connection:Certificate did not match expected hostname: incidentmanagement.uk-london-1.oraclecloud.com. Certificate: {'subject': ((('countryName', 'US'),), (('stateOrProvinceName', 'California'),), (('localityName', 'Redwood City'),), (('organizationName', 'Oracle Corporation'),), (('organizationalUnitName', 'Oracle OCI-PROD PHOENIX'),), (('commonName', 'incidentmanagement.us-phoenix-1.oraclecloud.com'),)), 'issuer': ((('countryName', 'US'),), (('organizationName', 'DigiCert Inc'),), (('commonName', 'DigiCert TLS RSA SHA256 2020 CA1'),)), 'version': 3, 'serialNumber': '018A1B883B3DC7DE1E44255E6CD03B5E', 'notBefore': 'May 20 00:00:00 2021 GMT', 'notAfter': 'May 25 23:59:59 2022 GMT', 'subjectAltName': (('DNS', 'incidentmanagement.us-phoenix-1.oraclecloud.com'),), 'OCSP': ('http://ocsp.digicert.com',), 'caIssuers': ('http://cacerts.digicert.com/DigiCertTLSRSASHA2562020CA1.crt',), 'crlDistributionPoints': ('http://crl3.digicert.com/DigiCertTLSRSASHA2562020CA1.crl', 'http://crl4.digicert.com/DigiCertTLSRSASHA2562020CA1.crl')}
WARNING:oci._vendor.urllib3.connection:Certificate did not match expected hostname: incidentmanagement.uk-london-1.oraclecloud.com. Certificate: {'subject': ((('countryName', 'US'),), (('stateOrProvinceName', 'California'),), (('localityName', 'Redwood City'),), (('organizationName', 'Oracle Corporation'),), (('organizationalUnitName', 'Oracle OCI-PROD PHOENIX'),), (('commonName', 'incidentmanagement.us-phoenix-1.oraclecloud.com'),)), 'issuer': ((('countryName', 'US'),), (('organizationName', 'DigiCert Inc'),), (('commonName', 'DigiCert TLS RSA SHA256 2020 CA1'),)), 'version': 3, 'serialNumber': '018A1B883B3DC7DE1E44255E6CD03B5E', 'notBefore': 'May 20 00:00:00 2021 GMT', 'notAfter': 'May 25 23:59:59 2022 GMT', 'subjectAltName': (('DNS', 'incidentmanagement.us-phoenix-1.oraclecloud.com'),), 'OCSP': ('http://ocsp.digicert.com',), 'caIssuers': ('http://cacerts.digicert.com/DigiCertTLSRSASHA2562020CA1.crt',), 'crlDistributionPoints': ('http://crl3.digicert.com/DigiCertTLSRSASHA2562020CA1.crl', 'http://crl4.digicert.com/DigiCertTLSRSASHA2562020CA1.crl')}
WARNING:oci._vendor.urllib3.connection:Certificate did not match expected hostname: incidentmanagement.uk-london-1.oraclecloud.com. Certificate: {'subject': ((('countryName', 'US'),), (('stateOrProvinceName', 'California'),), (('localityName', 'Redwood City'),), (('organizationName', 'Oracle Corporation'),), (('organizationalUnitName', 'Oracle OCI-PROD PHOENIX'),), (('commonName', 'incidentmanagement.us-phoenix-1.oraclecloud.com'),)), 'issuer': ((('countryName', 'US'),), (('organizationName', 'DigiCert Inc'),), (('commonName', 'DigiCert TLS RSA SHA256 2020 CA1'),)), 'version': 3, 'serialNumber': '018A1B883B3DC7DE1E44255E6CD03B5E', 'notBefore': 'May 20 00:00:00 2021 GMT', 'notAfter': 'May 25 23:59:59 2022 GMT', 'subjectAltName': (('DNS', 'incidentmanagement.us-phoenix-1.oraclecloud.com'),), 'OCSP': ('http://ocsp.digicert.com',), 'caIssuers': ('http://cacerts.digicert.com/DigiCertTLSRSASHA2562020CA1.crt',), 'crlDistributionPoints': ('http://crl3.digicert.com/DigiCertTLSRSASHA2562020CA1.crl', 'http://crl4.digicert.com/DigiCertTLSRSASHA2562020CA1.crl')}
WARNING:oci._vendor.urllib3.connection:Certificate did not match expected hostname: incidentmanagement.uk-london-1.oraclecloud.com. Certificate: {'subject': ((('countryName', 'US'),), (('stateOrProvinceName', 'California'),), (('localityName', 'Redwood City'),), (('organizationName', 'Oracle Corporation'),), (('organizationalUnitName', 'Oracle OCI-PROD PHOENIX'),), (('commonName', 'incidentmanagement.us-phoenix-1.oraclecloud.com'),)), 'issuer': ((('countryName', 'US'),), (('organizationName', 'DigiCert Inc'),), (('commonName', 'DigiCert TLS RSA SHA256 2020 CA1'),)), 'version': 3, 'serialNumber': '018A1B883B3DC7DE1E44255E6CD03B5E', 'notBefore': 'May 20 00:00:00 2021 GMT', 'notAfter': 'May 25 23:59:59 2022 GMT', 'subjectAltName': (('DNS', 'incidentmanagement.us-phoenix-1.oraclecloud.com'),), 'OCSP': ('http://ocsp.digicert.com',), 'caIssuers': ('http://cacerts.digicert.com/DigiCertTLSRSASHA2562020CA1.crt',), 'crlDistributionPoints': ('http://crl3.digicert.com/DigiCertTLSRSASHA2562020CA1.crl', 'http://crl4.digicert.com/DigiCertTLSRSASHA2562020CA1.crl')}
WARNING:oci._vendor.urllib3.connection:Certificate did not match expected hostname: incidentmanagement.uk-london-1.oraclecloud.com. Certificate: {'subject': ((('countryName', 'US'),), (('stateOrProvinceName', 'California'),), (('localityName', 'Redwood City'),), (('organizationName', 'Oracle Corporation'),), (('organizationalUnitName', 'Oracle OCI-PROD PHOENIX'),), (('commonName', 'incidentmanagement.us-phoenix-1.oraclecloud.com'),)), 'issuer': ((('countryName', 'US'),), (('organizationName', 'DigiCert Inc'),), (('commonName', 'DigiCert TLS RSA SHA256 2020 CA1'),)), 'version': 3, 'serialNumber': '018A1B883B3DC7DE1E44255E6CD03B5E', 'notBefore': 'May 20 00:00:00 2021 GMT', 'notAfter': 'May 25 23:59:59 2022 GMT', 'subjectAltName': (('DNS', 'incidentmanagement.us-phoenix-1.oraclecloud.com'),), 'OCSP': ('http://ocsp.digicert.com',), 'caIssuers': ('http://cacerts.digicert.com/DigiCertTLSRSASHA2562020CA1.crt',), 'crlDistributionPoints': ('http://crl3.digicert.com/DigiCertTLSRSASHA2562020CA1.crl', 'http://crl4.digicert.com/DigiCertTLSRSASHA2562020CA1.crl')}
RequestException: OCIConnectionPool(host='incidentmanagement.uk-london-1.oraclecloud.com', port=443): Max retries exceeded with url: /20181231/v2/incidents?compartmentId=ocid1.tenancy.oc1..******* (Caused by SSLError(SSLCertVerificationError("hostname 'incidentmanagement.uk-london-1.oraclecloud.com' doesn't match 'incidentmanagement.us-phoenix-1.oraclecloud.com'")))


**SDK**

public IEnumerable<IncidentSummary> ListIncidents(string csi, string tenancyId, string homeRegion, string ocid, string problemType)
		{
			var request = new ListIncidentsRequest()
				{Csi = csi, CompartmentId = tenancyId, Homeregion = homeRegion, Ocid = ocid};

			var responseEnum = _client.Paginators.ListIncidentsResponseEnumerator(request);
			return responseEnum.SelectMany(r => r.Items).ToList();
		}

**Comment by github-anurag** [comment]
Hi @jbcintra 
Can you answer a few questions that can help us identify the root cause:-
- do you hit the same issue against other APIs in same service (from same box, targeting same region)?
- do you hit the same issue against same API of same service (from same box), targeting different region?
- do the hit the same issue against an API of another service, such as ListUsers (from same box, targeting same region)? (You don't have this issue I believe)

**Comment by github-anurag** [comment]
@jbcintra 
This issue might be due to the openssl installed in your machine not supporting SNI. Can you check if updating openssl on your machine can resolve this issue.

**Comment by jbcintra** [comment]
Hi @github-anurag , I've tried this on a dev workstation (Win10 Pro, fully patched, latest CLI, latest Vis Studio) via the internet, and on an OCI hosted Windows 2016 Server, routing via the Service Gateway.  Both had the same certificate issues.  Tried with CLI and dotnet.  I'll be away now and unable to test any further for a week.

**Comment by jodoglevy** [comment]
@jbcintra what version(s) of openssl do you have installed on these boxes?

**Comment by github-anurag** [comment]
Hi @jbcintra 
Were you able to get this issue resolved?

**Comment by jbcintra** [comment]
Hi, I've been on holiday, just getting back up to speed and will check if this is still having the same issue.

**Comment by jbcintra** [comment]
I get the same error running it with the CLI, which is using pyopenssl 19.1.0.

I'm not sure what openssl that Visual Studio is using for the dotnet SDK, presumably that's referenced via the SDK?

**Comment by jbcintra** [comment]
Just updated the CLI, still the same ssl py version. It appears to be trying to connect to a US api, but erroring at a UK api?

oci support incident list --csi ******** --compartment-id ocid1.tenancy.oc1..****** --ocid ocid1.user.oc1..****** --homeregion us-phoenix-1  --profile ****

WARNING:oci._vendor.urllib3.connection:Certificate did not match expected hostname: incidentmanagement.uk-london-1.oraclecloud.com. Certificate: {'subject': ((('countryName', 'US'),), (('stateOrProvinceName', 'California'),), (('localityName', 'Redwood City'),), (('organizationName', 'Oracle Corporation'),), (('organizationalUnitName', 'Oracle OCI-PROD PHOENIX'),), (('commonName', 'incidentmanagement.us-phoenix-1.oraclecloud.com'),)), 'issuer': ((('countryName', 'US'),), (('organizationName', 'DigiCert Inc'),), (('commonName', 'DigiCert TLS RSA SHA256 2020 CA1'),)), 'version': 3, 'serialNumber': '018A1B883B3DC7DE1E44255E6CD03B5E', 'notBefore': 'May 20 00:00:00 2021 GMT', 'notAfter': 'May 25 23:59:59 2022 GMT', 'subjectAltName': (('DNS', 'incidentmanagement.us-phoenix-1.oraclecloud.com'),), 'OCSP': ('http://ocsp.digicert.com',), 'caIssuers': ('http://cacerts.digicert.com/DigiCertTLSRSASHA2562020CA1.crt',), 'crlDistributionPoints': ('http://crl3.digicert.com/DigiCertTLSRSASHA2562020CA1.crl', 'http://crl4.digicert.com/DigiCertTLSRSASHA2562020CA1.crl')}
WARNING:oci._vendor.urllib3.connection:Certificate did not match expected hostname: incidentmanagement.uk-london-1.oraclecloud.com. Certificate: {'subject': ((('countryName', 'US'),), (('stateOrProvinceName', 'California'),), (('localityName', 'Redwood City'),), (('organizationName', 'Oracle Corporation'),), (('organizationalUnitName', 'Oracle OCI-PROD PHOENIX'),), (('commonName', 'incidentmanagement.us-phoenix-1.oraclecloud.com'),)), 'issuer': ((('countryName', 'US'),), (('organizationName', 'DigiCert Inc'),), (('commonName', 'DigiCert TLS RSA SHA256 2020 CA1'),)), 'version': 3, 'serialNumber': '018A1B883B3DC7DE1E44255E6CD03B5E', 'notBefore': 'May 20 00:00:00 2021 GMT', 'notAfter': 'May 25 23:59:59 2022 GMT', 'subjectAltName': (('DNS', 'incidentmanagement.us-phoenix-1.oraclecloud.com'),), 'OCSP': ('http://ocsp.digicert.com',), 'caIssuers': ('http://cacerts.digicert.com/DigiCertTLSRSASHA2562020CA1.crt',), 'crlDistributionPoints': ('http://crl3.digicert.com/DigiCertTLSRSASHA2562020CA1.crl', 'http://crl4.digicert.com/DigiCertTLSRSASHA2562020CA1.crl')}
WARNING:oci._vendor.urllib3.connection:Certificate did not match expected hostname: incidentmanagement.uk-london-1.oraclecloud.com. Certificate: {'subject': ((('countryName', 'US'),), (('stateOrProvinceName', 'California'),), (('localityName', 'Redwood City'),), (('organizationName', 'Oracle Corporation'),), (('organizationalUnitName', 'Oracle OCI-PROD PHOENIX'),), (('commonName', 'incidentmanagement.us-phoenix-1.oraclecloud.com'),)), 'issuer': ((('countryName', 'US'),), (('organizationName', 'DigiCert Inc'),), (('commonName', 'DigiCert TLS RSA SHA256 2020 CA1'),)), 'version': 3, 'serialNumber': '018A1B883B3DC7DE1E44255E6CD03B5E', 'notBefore': 'May 20 00:00:00 2021 GMT', 'notAfter': 'May 25 23:59:59 2022 GMT', 'subjectAltName': (('DNS', 'incidentmanagement.us-phoenix-1.oraclecloud.com'),), 'OCSP': ('http://ocsp.digicert.com',), 'caIssuers': ('http://cacerts.digicert.com/DigiCertTLSRSASHA2562020CA1.crt',), 'crlDistributionPoints': ('http://crl3.digicert.com/DigiCertTLSRSASHA2562020CA1.crl', 'http://crl4.digicert.com/DigiCertTLSRSASHA2562020CA1.crl')}
WARNING:oci._vendor.urllib3.connection:Certificate did not match expected hostname: incidentmanagement.uk-london-1.oraclecloud.com. Certificate: {'subject': ((('countryName', 'US'),), (('stateOrProvinceName', 'California'),), (('localityName', 'Redwood City'),), (('organizationName', 'Oracle Corporation'),), (('organizationalUnitName', 'Oracle OCI-PROD PHOENIX'),), (('commonName', 'incidentmanagement.us-phoenix-1.oraclecloud.com'),)), 'issuer': ((('countryName', 'US'),), (('organizationName', 'DigiCert Inc'),), (('commonName', 'DigiCert TLS RSA SHA256 2020 CA1'),)), 'version': 3, 'serialNumber': '018A1B883B3DC7DE1E44255E6CD03B5E', 'notBefore': 'May 20 00:00:00 2021 GMT', 'notAfter': 'May 25 23:59:59 2022 GMT', 'subjectAltName': (('DNS', 'incidentmanagement.us-phoenix-1.oraclecloud.com'),), 'OCSP': ('http://ocsp.digicert.com',), 'caIssuers': ('http://cacerts.digicert.com/DigiCertTLSRSASHA2562020CA1.crt',), 'crlDistributionPoints': ('http://crl3.digicert.com/DigiCertTLSRSASHA2562020CA1.crl', 'http://crl4.digicert.com/DigiCertTLSRSASHA2562020CA1.crl')}
WARNING:oci._vendor.urllib3.connection:Certificate did not match expected hostname: incidentmanagement.uk-london-1.oraclecloud.com. Certificate: {'subject': ((('countryName', 'US'),), (('stateOrProvinceName', 'California'),), (('localityName', 'Redwood City'),), (('organizationName', 'Oracle Corporation'),), (('organizationalUnitName', 'Oracle OCI-PROD PHOENIX'),), (('commonName', 'incidentmanagement.us-phoenix-1.oraclecloud.com'),)), 'issuer': ((('countryName', 'US'),), (('organizationName', 'DigiCert Inc'),), (('commonName', 'DigiCert TLS RSA SHA256 2020 CA1'),)), 'version': 3, 'serialNumber': '018A1B883B3DC7DE1E44255E6CD03B5E', 'notBefore': 'May 20 00:00:00 2021 GMT', 'notAfter': 'May 25 23:59:59 2022 GMT', 'subjectAltName': (('DNS', 'incidentmanagement.us-phoenix-1.oraclecloud.com'),), 'OCSP': ('http://ocsp.digicert.com',), 'caIssuers': ('http://cacerts.digicert.com/DigiCertTLSRSASHA2562020CA1.crt',), 'crlDistributionPoints': ('http://crl3.digicert.com/DigiCertTLSRSASHA2562020CA1.crl', 'http://crl4.digicert.com/DigiCertTLSRSASHA2562020CA1.crl')}
RequestException: OCIConnectionPool(host='incidentmanagement.uk-london-1.oraclecloud.com', port=443): Max retries exceeded with url: /20181231/v2/incidents?compartmentId=ocid1.tenancy.oc1..**** (Caused by SSLError(SSLCertVerificationError("hostname 'incidentmanagement.uk-london-1.oraclecloud.com' doesn't match 'incidentmanagement.us-phoenix-1.oraclecloud.com'")))

**Comment by github-anurag** [comment]
@jbcintra 
Can you share the version of openssl on your machine?
We can get the openssl version from cmd using:- `openssl version -a`

**Comment by jbcintra** [comment]
Hi, there is no openssl in the path.  I have 6 copies installed throughout the system...

msys64 1.1.1b Feb 19
Git 1.1.1k Mar 21
SQL2019 1..1a Nov 18
Vis Studio (presumably C# SDK is calling this?) 1.1.1c May 2019

**Comment by jbcintra** [comment]
I've set the path to use the Git latest version, and re-run the CLI command, with the same error output.

**Comment by github-anurag** [comment]
@jbcintra
The CimsService just verified that they only support the two US regions (PHX and IAD).

The CLI command for the US region fails because the profile you are using most likely uses the region as UK so the endpoint for the API is UK and causes the failure. A solution would be to update the region in the profile you are using or to pass `--region` to the CLI command.

```
oci support incident list --csi ******** --compartment-id ocid1.tenancy.oc1..****** --ocid ocid1.user.oc1..****** --homeregion us-phoenix-1 --profile **** --region us-phoenix-1
```

Let me know if this resolves the issue. I will file a ticket on them to improve the error message when using other regions.

**Comment by jbcintra** [comment]
Hi @github-anurag, good to get that from the team.  I've just tried with those --region/--homeregion additions with the CLI, and now get a 401 Auth Failed error, so I can just check on permissions.   I'll look to get that factored into the SDK code once I get it working in the CLI.  Thanks for chasing this up with them!

**Comment by jbcintra** [comment]
Looking at the SDK code, there is no Region parameter to ListIncidents, which is in the CLI and is needed to reach the API.  Will the credentials generated for this call have to have their region overridden to work?

**Comment by github-anurag** [comment]
@jbcintra 
Either you can update the OCI Config Profile or you change the region for the clients using the following example as a reference:-

https://github.com/oracle/oci-dotnet-sdk/blob/master/Examples/ChangeRegionExample.cs

**Comment by jbcintra** [comment]
Thanks @github-anurag , I'll try the SetRegion to keep it cleaner.  Once I've checked on the permissions tomorrow, I'll update here just to confirm, though from the CLI changes that seems to be on track which is great.

**Comment by jbcintra** [comment]
Hi @github-anurag ,  just to check on this...
I'm getting 401 errors but have permissions to the CSI via support.oracle.com.

Wanted to check, I have access via support, but my support account won't as far as I know correlate to my OCID in the tenancy in question. Should it be an OCID from my Oracle support user, instead of from the customer tenancy?  I can't see how it would validate my access otherwise, unless somehow the accounts need to be linked together?

**Comment by jbcintra** [comment]
"code": "AUTH_FAILED",
    "message": "Authentication failed for the request input. HttpStatus 401",
    "opc-request-id": "E1E80E455F8A4A328FA1058B08DAA322/70695EF174EE234CD4EBE35567696587/544F01CBA07E876C092203320C3AD9B2"
    
    In case request id helps to understand why

**Comment by github-anurag** [comment]
@jbcintra 
I have forwarded this info to the relevant team. I will get back to you with their response.

**Comment by github-anurag** [comment]
@jbcintra 
Can you check if you can use APIs from other services (Non-CIMS) using the same config / box and region ?

**Comment by jbcintra** [comment]
Hi, our own tenancy is in Phoenix and I've used 151 OCI APIs on that tenancy without problem, using the same codebase, albeit with credentials related to that tenancy.

**Comment by github-anurag** [comment]
@jbcintra 
Can you confirm if you can use any of those other APIs with the exact same user, region and config (which you used for the CIMS service) without the authentication issue?

**Comment by jbcintra** [comment]
Hi, yes the credentials I'm testing with are my own, used for admin & audit.  How does Oracle correlate my company details in support.oracle.com, with an OCID in a tenancy??  This is a customer tenancy that we built & manage. It is federated IDCS, and does have my corp email address in the user details.

**Comment by github-anurag** [comment]
@jbcintra 
For the "opc-request-id": "E1E80E455F8A4A328FA1058B08DAA322/70695EF174EE234CD4EBE35567696587/544F01CBA07E876C092203320C3AD9B2"
The tenancy that you are using is not subscribed to the PHX region so that is why the authentication is failing.

**Comment by jbcintra** [comment]
Hi, I was told that this API service is only available in PHX, not the UK.  And to override the client setup to use PHX.  I presumed from that, that Support APIs globally were all running from PHX, and would support all regions globally.  So do I take it that in the UK it's not possible to use this API to track support issues?  If that's the case, is there an expected release date for these services into the UK?

**Comment by jayeshgangadharan** [comment]
@jbcintra We are working on the UK region at the moment. ETA is end of September (early october worst case scenario) but support is a tenancy based resource and not region specific.

currently we support Phoenix or Ashburn, are you subscribed to Ashburn ?

**Comment by jbcintra** [comment]
Thanks @jayeshgangadharan. We've got our own tenancy in PHX, but have our largest customer tenancies in LDN, and it would be  good for ops tracking - and management reporting - to add incident tracking in automatically.  As we onboard more in PHX that we fully manage I'll look into retrying the APIs there, else will wait till they're released in the UK.  Will other EU regions get the APIs at a similar time?

**Comment by jayeshgangadharan** [comment]
Thank you @jbcintra. our plan is to go global by mid october timeframe. let me know if you have any issues with PHX or IAD

**Comment by jbcintra** [comment]
Hi @github-anurag, I've just got to check back on this, and in both dotnet SDK and CLI, I'm getting the same certificate errors, which indicated the service wasn't yet available in the UK. It was to be been live here end of year, so well overdue.   Is there a status page where I can check on this particular CIMS API set being available in the UK, else could you please check on current status for me.  Thanks, Justin.

**Comment by github-anurag** [comment]
@jbcintra 
Thank you for bringing this up again. I will check in with the CIMS team and let you know the current status of this support.

Apologies for any inconvenience caused.

**Comment by buzhidao77** [comment]
@jbcintra FYI you can always refer to the public documentation to check the endpoints available to each public service, e.g. https://docs.oracle.com/en-us/iaas/api/#/en/incidentmanagement/20181231/
This service is only available to 2 regions at this moment.

**Comment by jbcintra** [comment]
Thanks @github-anurag  and @buzhidao77.  Any plans for when it will be available in the UK, as it was due months ago?

**Comment by vinaypebbeti** [comment]
Hi @jbcintra, we are not yet available on any region other than Ashburn and Phoenix. We have plan to scale up to other regions. We will notify in this thread once we are available in your desired Region

**Comment by jbcintra** [comment]
Thanks @vinaypebbeti .

I'd hope this would have been deployed/enabled now in European key regions, as it's almost 18 months.  Is there any schedule to get this out there, it would be very useful, especially chasing SRs across multiple clients.
