### ISSUE TITLE
Long Running Consume Messages Exemple

### ISSUE THREAD

**Issue by juniorschen** [oracle/oci-dotnet-sdk#93]
Hi a long running consumption example would be very interesting

**Comment by github-anurag** [comment]
@juniorschen 
Are you looking for an example for consuming streams? Hope this helps:-
https://github.com/oracle/oci-dotnet-sdk/blob/master/Examples/StreamingExample.cs

**Comment by jodoglevy** [comment]
Yes @juniorschen as @github-anurag mentions, we need to know which service's messages you mean you'd like to consume, in order to help

**Comment by jodoglevy** [comment]
@juniorschen  ping - are you still in need of assistance here?

**Comment by jodoglevy** [comment]
@juniorschen since we've haven't heard from you in a while, I'm going to close this. But feel free to reopen if you are still in need of assistance.
