### ISSUE TITLE
Getting db token and private key from IAM using OCI .NET SDK

### ISSUE THREAD

**Issue by vikram055** [oracle/oci-dotnet-sdk#94]
I'm trying to get a db token and a private key from IAM using OCI .NET SDK. It was supposed to be available in the oci .net sdk version- 29.2.0-preview.30793813. I installed the latest nuget package, 29.3.0, but I don't seem to find the required APIs/Classes which can be used for this purpose. Can you please help me in writing a sample .NET test case, which will use oci .net sdk to get the db token from the IAM? Is this functionality out yet? Is there any documentation available for this use case?

**Comment by github-anurag** [comment]
@vikram055 
I don't see the functionality you have mentioned in [IAM service APIs](https://docs.oracle.com/en-us/iaas/api/#/en/identity/20160918/ ). Can you let me know which API you are referring to from this list of APIs? If the API you have mentioned isn't listed here then its most likely that the functionality you are referring to hasn't been released to public yet.

**Comment by vikram055** [comment]
@github-anurag 
It doesn't look like that the API which I'm looking for is present in the given list. 
Please can you go through this java code- https://orahub.oci.oraclecorp.com/-/snippets/2269 , and let me know if the given functionality/APIs is available in the OCI .NET SDK? This java code basically generates a public/private key pair, and then uses the public key to get the scoped db token from IAM using OCI JAVA SDK. The API that it uses to get the db token is **GenerateScopedAccessTokenRequest**, and `**GenerateScopedAccessTokenDetails**`.

**Comment by github-anurag** [comment]
@vikram055 
Are you part of OCI? If so then please share your info and we can move this talk to internal channels and close the public issue.

**Comment by vikram055** [comment]
@github-anurag 
I'm not part of OCI team but Windows .Net team. Sure, we can talk about this internally. You can email me on vikram.b.kumar@oracle.com. Thanks!

**Comment by jodoglevy** [comment]
This functionality is not publicly available yet, hence it not being in the SDK yet.

**Comment by pfdsilva** [comment]
@jodoglevy When will the functionality be publicly available?

**Comment by jodoglevy** [comment]
@pfdsilva  if you are internal to Oracle, please reach out to me internally. The functionality would be available in the SDK on the first Tuesday on/after the general availability of the feature in OCI
